name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # Runs daily at 18:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile 3D Contribution Graph

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: "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"  # Replace this with your actual token
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push changes
        env:
          GITHUB_TOKEN: "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"  # Replace this with your actual token
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Updated 3D contribution graph"
          git push
