name: Geotrics

on:
  # Schedule updates every hour
  schedule:
    - cron: "0 * * * *"
  # Enable manual workflow dispatch and run on pushes to master/main
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Use the 'hades' branch if it exists, otherwise use 'main'
      - uses: haydenbanz/metrics@hades
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # User and template settings
          user: haydenbanz
          template: classic
          config_timezone: Asia/Kolkata


          plugin_music: yes
          plugin_music_limit: 5
          plugin_music_playlist: "https://embed.music.apple.com/in/playlist/best-of-2016-english/pl.5c31bfacf1e3411ab9b45994baf0fc60"

          plugin_rss: yes
          plugin_rss_limit: 6
          plugin_rss_source: "https://raw.githubusercontent.com/haydenbanz/haydenbanz.github.io/refs/heads/main/rss.xml"

