name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]  # Run daily at 16:00 UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate_metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Generate base metrics
        uses: haydenbanz/metrics@hades
        id: generate_base
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.base.svg
          user: haydenbanz
          base: header, activity, community, repositories, metadata
          output_action: save
          delay: 120
          plugins_errors_fatal: yes

      - name: Generate large display metrics
        uses: haydenbanz/metrics@hades
        id: generate_large_display
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.large.svg
          user: haydenbanz
          config_display: large
          output_action: save
          delay: 120
          plugins_errors_fatal: yes

      - name: Generate JSON metrics
        uses: haydenbanz/metrics@hades
        id: generate_json
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.example.json
          user: haydenbanz
          config_output: json
          output_action: save
          delay: 120
          plugins_errors_fatal: yes

      - name: Generate PNG metrics
        uses: haydenbanz/metrics@hades
        id: generate_png
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.example.png
          user: haydenbanz
          config_output: png
          output_action: save
          delay: 120
          plugins_errors_fatal: yes

      - name: Generate insights HTML metrics
        uses: haydenbanz/metrics@hades
        id: generate_insights
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.insights.html
          user: haydenbanz
          config_output: insights
          output_action: save
          delay: 120
          plugins_errors_fatal: yes

      - name: Upload metrics as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: metrics-artifacts
          path: |
            metrics.base.svg
            metrics.large.svg
            metrics.example.json
            metrics.example.png
            metrics.insights.html

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Update metrics [skip ci]" || echo "No changes to commit"
          git push origin HEAD
